/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    FillterCondition: typeof import('./src/components/FillterCondition.vue')['default']
  }
}
